name: fico_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  mime: ^1.0.0
  http_parser: ^4.0.2  # Downgrade a esta versión
  image_picker: ^0.8.7+3
  google_nav_bar: ^5.0.6
  file_picker: ^5.2.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0 
  shared_preferences: ^2.0.15
  crypto: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - web/icons/1.png
    - web/icons/microsoftlogo (1).png
    - web/icons/incorrecto.png
    - web/icons/LogoFico.png

